
name: AutoMation
on: [workflow_dispatch]
jobs:
  metrics:
    runs-on: ubuntu-20.04
    steps: 

      - name: Readme Profile Youtube
        continue-on-error: true
        uses: DenverCoder1/github-readme-youtube-cards@main
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          lang: "id"
          channel_id: UCRPx9vOpzqVwALIqYnJRhTw 
          readme_path: profile/README.md 