
name: AutoMation
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 0 */1 * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 

      - name: Readme Profile Youtube
        continue-on-error: true
        uses: DenverCoder1/github-readme-youtube-cards@main
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          lang: "id"
          channel_id: UCRPx9vOpzqVwALIqYnJRhTw 
          readme_path: profile/README.md 